export const post = [
  {
    id: 1,
    title: "취업",
    likes: "",
    date: "2022-08-01",
    type: "laws",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "1",
    views: "45",
  },
  {
    id: 2,
    title: "실업",
    likes: "",
    date: "2023-08-02",
    type: "laws",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "1",
    views: "45",
  },
  {
    id: 3,
    title: "보험",
    likes: "",
    date: "2023-08-01",
    type: "news",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "2",
    views: "45",
  },
  {
    id: 4,
    title: "임금",
    likes: "5",
    date: "2023-08-02",
    type: "community",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "2",
    views: "45",
  },
  {
    id: 5,
    title: "직장 내 괴롭힘",
    likes: "10",
    date: "2023-08-01",
    type: "community",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "3",
    views: "45",
  },
  {
    id: 6,
    title: "복리후생",
    likes: "5",
    date: "2023-09-01",
    type: "community",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "4",
    views: "45",
  },
  {
    id: 7,
    title: "복리후생",
    likes: "25",
    date: "2023-09-01",
    type: "community",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "4",
    views: "45",
  },
  {
    id: 8,
    title: "복리후생",
    likes: "5",
    date: "2023-09-01",
    type: "community",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "5",
    views: "45",
  },
  {
    id: 9,
    title: "복리후생",
    likes: "5",
    date: "2023-09-01",
    type: "community",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "5",
    views: "45",
  },
  {
    id: 10,
    title: "복리후생",
    likes: "5",
    date: "2023-09-01",
    type: "community",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "6",
    views: "45",
  },
  {
    id: 11,
    title: "복리후생",
    likes: "5",
    date: "2023-09-01",
    type: "community",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "6",
    views: "45",
  },
  {
    id: 12,
    title: "복리후생",
    likes: "5",
    date: "2023-09-01",
    type: "community",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "0",
    views: "45",
  },
  {
    id: 13,
    title: "복리후생",
    likes: "5",
    date: "2023-09-01",
    type: "community",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "취업",
    views: "0",
  },
  {
    id: 14,
    title: "복리후생",
    likes: "5",
    date: "2023-09-01",
    type: "community",
    contents:
      "취약계층이 어쩌구 저쩌구.을아ㅓ랑린어ㅣㄹㄴ어ㅣ런이ㅏ러ㅣㄴ아ㅓ린어ㅣ렁니ㅏ러ㅣㄴ아ㅓ린어리ㅓㅣ렁나ㅣ러ㅣㅏㅇ너리ㅏㅇ너리ㅏ어니렁널인",
    author: "author",
    tags: "0",
    views: "45",
  },
];
