export const post = [
  {
    id: 1,
    title: "취업",
    likes: "",
    date: "2022-08-01",
    type: "laws",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "취업",
    views: "45",
  },
  {
    id: 2,
    title: "실업",
    likes: "",
    date: "2023-08-02",
    type: "laws",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "취업",
    views: "45",
  },
  {
    id: 3,
    title: "보험",
    likes: "",
    date: "2023-08-01",
    type: "news",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "취업",
    views: "45",
  },
  {
    id: 4,
    title: "임금",
    likes: "35",
    date: "2023-08-02",
    type: "community",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "취업",
    views: "45",
  },
  {
    id: 5,
    title: "직장 내 괴롭힘",
    likes: "90",
    date: "2023-08-01",
    type: "community",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "취업",
    views: "45",
  },
  {
    id: 6,
    title: "복리후생",
    likes: "75",
    date: "2023-09-01",
    type: "community",
    contents: "취약계층이 어쩌구 저쩌구..",
    author: "author",
    tags: "취업",
    views: "45",
  },
];
